// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Home documents */
interface HomeDocumentData {
  /**
   * Seção do Titulo field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerTitle[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  containerTitle: prismic.GroupField<
    Simplify<HomeDocumentDataContainerTitleItem>
  >;
  /**
   * Seção Sobre Nós field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerAbout[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  containerAbout: prismic.GroupField<
    Simplify<HomeDocumentDataContainerAboutItem>
  >;
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Item in Home → Seção do Titulo
 *
 */
export interface HomeDocumentDataContainerTitleItem {
  /**
   * Titulo field in *Home → Seção do Titulo*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerTitle[].pageTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  pageTitle: prismic.TitleField;
  /**
   * Subtitulo field in *Home → Seção do Titulo*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerTitle[].pageSubtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  pageSubtitle: prismic.TitleField;
}
/**
 * Item in Home → Seção Sobre Nós
 *
 */
export interface HomeDocumentDataContainerAboutItem {
  /**
   * Titulo field in *Home → Seção Sobre Nós*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerAbout[].aboutTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  aboutTitle: prismic.TitleField;
  /**
   * Imagem field in *Home → Seção Sobre Nós*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerAbout[].aboutImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  aboutImage: prismic.ImageField<never>;
  /**
   * Texto field in *Home → Seção Sobre Nós*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.containerAbout[].aboutText
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  aboutText: prismic.RichTextField;
}
/**
 * Slice for *Home → Slice Zone*
 *
 */
type HomeDocumentDataSlicesSlice = BlogSlice;
/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;
export type AllDocumentTypes = HomeDocument;
/**
 * Primary content in Posts → Primary
 *
 */
interface BlogSliceDefaultPrimary {
  /**
   * Titulo field in *Posts → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.primary.postTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  postTitle: prismic.TitleField;
}
/**
 * Item in Posts → Items
 *
 */
export interface BlogSliceDefaultItem {
  /**
   * Texto field in *Posts → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].postText
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  postText: prismic.RichTextField;
  /**
   * Imagem field in *Posts → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].postImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  postImage: prismic.ImageField<never>;
}
/**
 * Default variation for Posts Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  Simplify<BlogSliceDefaultItem>
>;
/**
 * Slice variation for *Posts*
 *
 */
type BlogSliceVariation = BlogSliceDefault;
/**
 * Posts Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: `Blog`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomeDocumentData,
      HomeDocumentDataContainerTitleItem,
      HomeDocumentDataContainerAboutItem,
      HomeDocumentDataSlicesSlice,
      HomeDocument,
      AllDocumentTypes,
      BlogSliceDefaultPrimary,
      BlogSliceDefaultItem,
      BlogSliceDefault,
      BlogSliceVariation,
      BlogSlice,
    };
  }
}
