// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for page documents */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  meta_description: prismic.RichTextField;
  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  meta_image: prismic.ImageField<never>;
  /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  meta_title: prismic.KeyTextField;
}
/**
 * Slice for *page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = BlogSlice | AboutSlice | HeroSlice;
/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = PageDocument;
/**
 * Primary content in About → Primary
 *
 */
interface AboutSliceDefaultPrimary {
  /**
   * Titulo field in *About → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.aboutTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  aboutTitle: prismic.TitleField;
  /**
   * Texto field in *About → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.aboutText
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  aboutText: prismic.RichTextField;
  /**
   * Imagem field in *About → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.primary.aboutImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  aboutImage: prismic.ImageField<never>;
}
/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *About*
 *
 */
type AboutSliceVariation = AboutSliceDefault;
/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: `About`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;
/**
 * Primary content in Posts → Primary
 *
 */
interface BlogSliceDefaultPrimary {
  /**
   * Titulo field in *Posts → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.primary.postTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  postTitle: prismic.TitleField;
}
/**
 * Item in Posts → Items
 *
 */
export interface BlogSliceDefaultItem {
  /**
   * Texto field in *Posts → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].postText
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  postText: prismic.RichTextField;
  /**
   * Imagem field in *Posts → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].postImage
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  postImage: prismic.ImageField<never>;
  /**
   * Data do post field in *Posts → Items*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.items[].date
   * - **Documentation**: https://prismic.io/docs/core-concepts/timestamp
   *
   */
  date: prismic.TimestampField;
}
/**
 * Default variation for Posts Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogSliceDefaultPrimary>,
  Simplify<BlogSliceDefaultItem>
>;
/**
 * Slice variation for *Posts*
 *
 */
type BlogSliceVariation = BlogSliceDefault;
/**
 * Posts Shared Slice
 *
 * - **API ID**: `blog`
 * - **Description**: `Blog`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BlogSlice = prismic.SharedSlice<"blog", BlogSliceVariation>;
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
  /**
   * Titulo field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heroTitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroTitle: prismic.TitleField;
  /**
   * Subtitulo field in *Hero → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heroSubtitle
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  heroSubtitle: prismic.TitleField;
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault;
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocument,
      AllDocumentTypes,
      AboutSliceDefaultPrimary,
      AboutSliceDefault,
      AboutSliceVariation,
      AboutSlice,
      BlogSliceDefaultPrimary,
      BlogSliceDefaultItem,
      BlogSliceDefault,
      BlogSliceVariation,
      BlogSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
      HeroSlice,
    };
  }
}
