import Head from 'next/head'
import { createClient } from '../../prismicio'
import type { GetStaticPropsContext, InferGetStaticPropsType } from 'next'
import { SliceZone } from '@prismicio/react'
import {components} from "../../slices"

type PageProps = InferGetStaticPropsType<typeof getStaticProps>

export default function Home({page}: PageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SliceZone slices={page.data.slices} components={components}/>
      </main>
    </>
  )
}

export async function getStaticProps({previewData}: GetStaticPropsContext) {
  const client = createClient({ previewData })
  const page = await client.getByUID('page', "home")

  return {
    props: {
      page,
    },
  }
}

